import type { BuildingDef, BuildingId } from "./types";
import { BUILDING_IDS } from "./types";

export const BUILDINGS: BuildingDef[] = [
  {
    id: "cursor",
    name: "Curseur",
    plural: "Curseurs",
    description: "Autoclique le gros citron toutes les dix secondes.",
    flavor: "Aussi efficace qu'un stagiaire, mais il ne demande pas de tickets resto.",
    baseCost: 15,
    baseCps: 0.1,
    icon: "👆",
  },
  {
    id: "grandma",
    name: "Mamie citron",
    plural: "Mamies citron",
    description: "Une grand-mère qui presse des citrons avec amour (et les poignets).",
    flavor: "Elle jure que sa limonade soigne tout, y compris les impôts.",
    baseCost: 100,
    baseCps: 1,
    icon: "👵",
  },
  {
    id: "tree",
    name: "Citronnier",
    plural: "Citronniers",
    description: "Un arbre qui n'a qu'une idée en tête : plus de citrons.",
    flavor: "Arrosé exclusivement à l'eau plate. Le pétillant le rend nerveux.",
    baseCost: 1_100,
    baseCps: 8,
    icon: "🍋",
  },
  {
    id: "mine",
    name: "Mine de zestes",
    plural: "Mines de zestes",
    description: "Creuse la croûte terrestre à la recherche d'écorce premium.",
    flavor: "Les mineurs portent des casques jaunes, évidemment.",
    baseCost: 12_000,
    baseCps: 47,
    icon: "⛏️",
  },
  {
    id: "factory",
    name: "Usine de limonade",
    plural: "Usines de limonade",
    description: "Transforme les citrons en flux tendu, 24 heures sur 24.",
    flavor: "L'alarme incendie sent le citron confit.",
    baseCost: 130_000,
    baseCps: 260,
    icon: "🏭",
  },
  {
    id: "bank",
    name: "Banque citronnaise",
    plural: "Banques citronnaises",
    description: "Génère des citrons par intérêts composés et par magie comptable.",
    flavor: "Le taux d'acidité directeur est à 3,14 %.",
    baseCost: 1_400_000,
    baseCps: 1_400,
    icon: "🏦",
  },
  {
    id: "temple",
    name: "Temple du citron",
    plural: "Temples du citron",
    description: "Des prêtres pressent des offrandes au dieu de l'acidité.",
    flavor: "Le grand prêtre s'appelle zestès IV.",
    baseCost: 20_000_000,
    baseCps: 7_800,
    icon: "🛕",
  },
  {
    id: "wizard",
    name: "Tour d'alchimie",
    plural: "Tours d'alchimie",
    description: "Change l'eau, le sucre et un peu d'espoir en citrons.",
    flavor: "La recette exacte est « un peu de ça, beaucoup de ça ».",
    baseCost: 330_000_000,
    baseCps: 44_000,
    icon: "🧙",
  },
  {
    id: "shipment",
    name: "Vaisseau spatial",
    plural: "Vaisseaux spatiaux",
    description: "Importe des citrons depuis des planètes encore plus acides.",
    flavor: "Le carburant, c'est de la limonade concentrée. Ça pique les réacteurs.",
    baseCost: 5_100_000_000,
    baseCps: 260_000,
    icon: "🚀",
  },
  {
    id: "portal",
    name: "Portail",
    plural: "Portails",
    description: "Ouvre une brèche vers la dimension Citrusia.",
    flavor: "De l'autre côté, tout est jaune. Même les regrets.",
    baseCost: 75_000_000_000,
    baseCps: 1_600_000,
    icon: "🌀",
  },
  {
    id: "timemachine",
    name: "Machine temporelle",
    plural: "Machines temporelles",
    description: "Ramène des citrons du futur, où les arbres ont appris à courir.",
    flavor: "Attention aux paradoxes : ne mangez pas le citron qui vous a créé.",
    baseCost: 1_000_000_000_000,
    baseCps: 10_000_000,
    icon: "⏳",
  },
  {
    id: "condenser",
    name: "Condensateur",
    plural: "Condensateurs",
    description: "Compresse le vide jusqu'à en extraire un zeste.",
    flavor: "Si ça explose, au moins ça sentira bon.",
    baseCost: 14_000_000_000_000,
    baseCps: 65_000_000,
    icon: "⚛️",
  },
];

export const BUILDING_BY_ID: Record<BuildingId, BuildingDef> = Object.fromEntries(
  BUILDINGS.map((building) => [building.id, building]),
) as Record<BuildingId, BuildingDef>;

export function buildingIndex(id: BuildingId): number {
  return BUILDING_IDS.indexOf(id);
}
